- Dockerfile.dev
> Added Development Dockerfile

- src/components/end-user-contacts/end-user-contacts.tsx
- src/constants.ts
- src/services/widget-service.ts
https://github.com/buerokratt/Buerokratt-Chatbot/issues/92
Completes Changes Done in https://github.com/buerokratt/Buerokratt-Chatbot/pull/215
> 92 CSA can ask for End User contact information

- src/components/chat-keypad/chat-keypad.tsx
- src/constants.ts
- src/services/chat-service.ts
- src/slices/chat-slice.ts
- src/utils/debounce.ts
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/47
> 47 End User typed text can be seen by CSA while being typed

- src/components/chat-content/chat-content.tsx
- src/components/chat/chat.tsx
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/6
> 6 Automated ending of idle chat

- src/components/confirmation-modal/confirmation-modal-download.tsx
- src/components/confirmation-modal/confirmation-modal.module.scss
- src/constants.ts
- src/hooks/use-download-file.tsx
- src/services/chat-service.ts
- src/slices/chat-slice.ts
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/4
- Goes together with:
- https://github.com/buerokratt/Buerokratt-Chatbot/pull/232
- https://github.com/buerokratt/DataMapper/pull/12
> 4 Download/Forward finished chat

- src/App.tsx
- src/components/idle-chat-notification/idle-chat-notification.tsx
- src/slices/authentication-slice.ts
Reverts buerokratt/Chat-Widget#40
> Revert "Disabled Custom Jwt Extend"

- src/services/authentication-service.ts
Fixed Custom JWT Extend breaking SSE Connection
> Fixed Custom Jwt Extend

- src/components/chat-message/message-types/linkifier.tsx
Bugs Addressed:
- Allowed http, https and www in links sent
> Modified Linkifier regex

- package-lock.json
- package.json
- src/components/chat/chat.tsx
- src/components/confirmation-modal/confirmation-modal-nps.tsx
- src/components/idle-chat-notification/idle-chat-notification.tsx
- src/components/profile/profile.tsx
- src/components/unavailable-end-user-contacts/unavailable-end-user-contacts.tsx
- src/constants.ts
- src/model/organization-working-time-model.ts
- src/services/chat-service.test.ts
- src/services/chat-service.ts
- src/slices/chat-slice.ts
- src/test-initial-states.ts
- src/translations/en/common.json
- src/translations/et/common.json
- src/utils/holidays.ts
- src/utils/state-management-utils.ts
Bugs Addressed:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1#issuecomment-1698993851
> Bug Ask End User's contacts when chatbot is unable to reply and CSA is not present

- src/hooks/use-get-chat.ts
- src/hooks/use-get-new-messages.ts
- src/services/sse-service.ts
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/326
> Improve Server-sent events implementation

- src/components/confirmation-modal/confirmation-modal-download.tsx
Bugs Addressed:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/4#issuecomment-1801819630
> Bug Forward Finished Chat

- src/components/end-user-contacts/end-user-contacts.tsx
- src/components/unavailable-end-user-contacts/unavailable-end-user-contacts.tsx
- src/hooks/use-message-validator.ts
- src/services/chat-service.ts
- src/slices/chat-slice.ts
- src/utils/chat-utils.ts
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/92
> CSA can ask for End User contact information 

- src/constants.ts
- src/hooks/use-authentication.ts
- src/services/chat-service.ts
- Fixed Build Issue
- Modified Title and name visibility endpoints
> Hot Fix Build Issue

- src/components/chat-keypad/chat-keypad.tsx
- Changed Preview debounce time from 300 to 1000 ms
> Enhanced Debounce Time

- src/components/chat-message/message-types/admin-message.tsx
- src/model/message-model.ts
Fixed Bugs:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/10#issuecomment-1893386974
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/10#issuecomment-1893389004
> Hot Fix CSA Title

- src/services/chat-service.ts
- src/slices/chat-slice.ts
- Modified Messages and chat endpoints call
> Hot Fix Authentication Callback

- src/services/chat-service.ts
- Changed Endpoints from get to post
> Hot Fix Auth Callback

- src/services/widget-service.ts
- src/utils/auth-utils.ts
- Modified Authenticate User Endpoint
> Hot Fix Authenticate User

- src/utils/auth-utils.ts
> Hot fix redirection

- src/App.tsx
- src/hooks/use-authentication.ts
- src/hooks/use-get-chat.ts
- src/utils/auth-utils.ts
- Fixed Tara Authentication Callback
> Fixed Tara Authentication Callback

- src/components/end-user-contacts/end-user-contacts.tsx
- src/components/unavailable-end-user-contacts/unavailable-end-user-contacts.tsx
- src/utils/chat-utils.ts
Bugs Addressed:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/92#issuecomment-1892169454
> Hot fix Ask for Contacts Modal

- src/services/chat-service.test.ts
- src/services/chat-service.ts
- src/slices/chat-slice.ts
Related Tasks:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/374
> Chats Finished With Contacts

- src/utils/auth-utils.ts
- Modified Cookie Check
Related Bugs:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/111#issuecomment-1943823296
> Modified Cookie Check

- src/components/chat-message/chat-message.tsx
- src/components/end-user-contacts/end-user-contacts.tsx
- src/components/unavailable-end-user-contacts/unavailable-end-user-contacts.tsx
- src/services/chat-service.ts
- src/slices/chat-slice.ts
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1#issuecomment-1952320948
Combined with: 
- https://github.com/buerokratt/Buerokratt-Chatbot/pull/463
> Add user comment to user contact info

- src/components/end-user-contacts/end-user-contacts.tsx
- src/components/unavailable-end-user-contacts/unavailable-end-user-contacts.tsx
- src/hooks/use-reload-chat-end-effect.ts
Fixed Contact and unavailable UI Glitch
> Hot fix widget contact ui

- src/components/chat-content/chat-content.tsx
- src/components/chat/chat.tsx
- src/components/waiting-time-notification/waiting-time-notification-form.tsx
- src/components/waiting-time-notification/waiting-time-notification.module.scss
- src/components/waiting-time-notification/waiting-time-notification.tsx
- src/hooks/use-estimated-waiting-time.ts
- src/hooks/use-name-title-visibility.ts
- src/mocks/handlers.ts
- src/mocks/responses/get-waiting-time.json
- src/services/chat-service.ts
- src/slices/chat-slice.ts
- src/utils/format-time.ts
- src/utils/parse-string-number.ts
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/445#issuecomment-1980265433
Combined with:
- https://github.com/buerokratt/Buerokratt-Chatbot/pull/470
> Fix Queue Number issue

- src/components/chat-content/chat-content.tsx
- src/components/chat/chat.tsx
- src/components/waiting-time-notification/waiting-time-notification.tsx
- src/hooks/use-queue-counter.ts
- src/slices/chat-slice.ts
- src/utils/format-time.ts
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/445
- https://github.com/buerokratt/Buerokratt-Chatbot/pull/471
> Queue Numbers Hotfix

- src/utils/auth-utils.ts
> Hot Fix Tara Redirection Url

- src/services/sse-service.ts
> Console Error

- src/components/profile/profile.module.scss
- src/components/profile/profile.tsx
> Widget Logo Style

- src/components/chat-feedback/chat-feedback.module.scss
- src/components/chat-feedback/chat-feedback.tsx
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/574
> BUG FIX - User is not able to download chat if CSA ends it

- Dockerfile
- src/components/chat/chat.tsx
- src/hooks/useWindowDimensions.ts
Related Task:
- https://github.com/buerokratt/Chat-Widget/issues/200
> Hot Fix Widget Responsiveness

- Dockerfile
- Dockerfile.dev
- README.md
- docker-compose.yml
- public/env-config.js
- src/App.tsx
- src/constants.ts
- src/setupTests.ts
- webpack.config.js
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/641
> Hot-fix for `ENABLE_HIDDEN_FEATURES` environment variable

- src/utils/holidays.ts
- Only Added Public Holidays and removed important days
> Enhancement Holidays List

- src/components/chat-message/message-types/admin-message.tsx
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/682#issuecomment-2158357071
- https://github.com/buerokratt/Buerokratt-Chatbot/pull/697
> Display CSA title instead of the fallbacks.

- src/App.tsx
- src/components/chat-content/chat-content.tsx
- src/hooks/use-name-title-visibility.ts
- src/slices/chat-slice.ts
- src/utils/chat-utils.ts
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/682#issuecomment-2158357071
> Prevent duplicate messages and fix title visibility

- src/hooks/use-authentication.ts
- src/services/authentication-service.ts
- src/utils/auth-utils.ts
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/682#issuecomment-2158386979
> Fetch user info on refresh

- src/components/chat-content/chat-content.tsx
- src/components/chat-message/loading-animation.scss
- src/components/chat-message/message-types/loading-message.tsx
- src/components/chat/chat.tsx
- src/components/response-error-notification/response-error-notification.module.scss
- src/components/response-error-notification/response-error-notification.tsx
- src/slices/chat-slice.ts
- src/test-initial-states.ts
- src/translations/en/common.json
- src/translations/et/common.json
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/738
> Understanding if bot is broken or thinking

- src/components/chat-message/chat-message.tsx
- src/constants.ts
- src/translations/en/common.json
- src/translations/et/common.json
- added value to CHAT_EVENTS
- added notification translation
- added event handling
> Notify end user that chat has been taken over by CSA (#246)

- src/components/chat-message/message-types/linkifier.tsx
- Added Bold Text Detection
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/885
> Hot-Fix: Bold Text Detection

- src/components/chat-keypad/chat-keypad.module.scss
- src/components/chat-keypad/chat-keypad.tsx
- src/components/chat-message/chat-message.module.scss
- src/components/chat-message/message-types/admin-message.tsx
- src/components/chat-message/message-types/client-message.tsx
- src/utils/chat-utils.ts
Related task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/910
> Fix parsing percentages in chat

- src/hooks/use-get-emergency-notice.ts
- src/slices/chat-slice.ts
Related task:
- https://github.com/buerokratt/Chat-Widget/issues/323
> Fix emergency notice position

- README.md
- public/env-config.js
- public/iframe-index.html
- public/widget-index.html
- src/App.tsx
- src/components/chat/chat.tsx
- src/components/profile/profile.tsx
- src/setupTests.ts
> Add Iframe Support

- src/components/chat-message/loading-animation.scss
> Hot Fix Body Override

- src/components/chat-message/message-types/Markdownify.tsx
- Fixed Opening Links in new tab
> Hot-Fix: Open links in new tab

- src/components/chat-header/widget-details.tsx
- Removed auth button from chat settings.
Related [task](https://github.com/buerokratt/Chat-Widget/issues/330).
> 330 Authentication in chat

- src/components/chat-message/message-types/Markdownify.tsx
- src/components/response-error-notification/response-error-notification.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/941
> BUG: Chat will not end automatically after error message when End User choses to close the chat

- src/components/profile/profile.module.scss
- Added Adam sans-serif font to greeting message instead of default anino font
> Change greeting message font

- src/components/chat-message/message-types/Markdownify.tsx
- Added Image Support to messages
> Added Image Url Support

- public/iframe-index.html
- public/index.html
- public/widget-index.html
Related Task:
- https://github.com/buerokratt/Chat-Widget/issues/342
> BUG: The widget does not get zoomed in when typing on mobile

- src/slices/chat-slice.ts
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1024
> End user typing words visible to CSA

- src/hooks/use-message-validator.ts
- src/translations/en/common.json
- src/translations/et/common.json
This PR is related to https://github.com/buerokratt/Buerokratt-Chatbot/issues/1073
> Implement character limit

- src/components/chat-message/message-types/Markdownify.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1062
> Hyperlink Support

- src/components/chat-message/message-types/Markdownify.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1134
> Enhance Markdown Parsing

- src/model/message-model.ts
- src/slices/chat-slice.ts
Implement handling edited messages.
This PR is related to issue https://github.com/buerokratt/Buerokratt-Chatbot/issues/1104
> Implement handling edited messages

- src/hooks/use-reload-chat-end-effect.ts
- src/utils/browser-utils.ts
> Merging dev to test

- src/hooks/use-get-emergency-notice.ts
Related Bug:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/936#issuecomment-2639799855
> Hot-Fix: Changes-regarding-emergency-notice

- src/components/chat-content/chat-content.tsx
- src/components/chat-message/chat-message.module.scss
- src/components/chat-message/message-types/client-message.tsx
- src/slices/chat-slice.ts
- src/static/icons/outline-error.svg
- src/test-initial-states.ts
- src/translations/en/common.json
- src/translations/et/common.json
Implement delete and resend for failed messages.
This PR is related to issue https://github.com/buerokratt/Buerokratt-Chatbot/issues/1142.
> Implement delete and resend for failed messages

- src/hooks/use-reload-chat-end-effect.ts
- src/services/chat-service.ts
Related task: https://github.com/buerokratt/Buerokratt-Chatbot/issues/1117
> 1117 Fix terminating chats on tab close

- src/components/chat-message/message-types/Markdownify.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1191
> Encoding/decoding symbols in LLM messages

- public/env-config.js
- public/widget-index.html
- src/setupTests.ts
Related Task:
- https://github.com/buerokratt/Buerokratt-DSL/issues/69
> Adding Project Layer To Repos

- package.json
- src/slices/chat-slice.ts
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1182
> User device is not showing correctly

- package.json
- src/components/ask-forward-to-csa-modal/ask-forward-to-csa-modal.module.scss
- src/components/button/button.module.scss
- src/components/chat-content/chat-content.module.scss
- src/components/chat-feedback/chat-feedback.module.scss
- src/components/chat-keypad/chat-keypad.module.scss
- src/components/chat-message/chat-message.module.scss
- src/components/chat-message/message-types/Markdownify.tsx
- src/components/chat/chat.module.scss
- src/components/confirmation-modal/confirmation-modal.module.scss
- src/components/idle-chat-notification/idle-chat-notification.module.scss
- src/components/online-status-notification/online-status-notification.module.scss
- src/components/profile/profile.module.scss
- src/components/response-error-notification/response-error-notification.module.scss
- src/components/stars/stars.module.scss
- src/components/waiting-time-notification/waiting-time-notification.module.scss
- Removed normalize imports
- Reverted hyperlink changes.
Related [task](https://github.com/buerokratt/Chat-Widget/issues/384).
> feat(384): removed normalize

- package.json
- src/slices/chat-slice.ts
- Fixated markdown-to-jsx to version 7.7.3
> Hot-fix: Markdown To JSX Version

- src/services/http-service.ts
- src/services/notification-service.ts
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1231
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1192
> Hot-Fix: Browsers reading 300 responses from disk cache

- src/hooks/use-authentication.ts
- src/slices/chat-slice.ts
- src/utils/auth-utils.ts
Related Task:
- https://github.com/buerokratt/Chat-Widget/issues/410
> Authenticate users using cookie

- src/components/chat-message/message-types/Markdownify.tsx
- src/components/chat-message/message-types/client-message.tsx
Related task and comment: https://github.com/buerokratt/Buerokratt-Chatbot/issues/1258
> 1258: Prevent end-users from spoofing URLs in messages

- Dockerfile
- README.md
- nginx/http-nginx.conf
- package.json
- public/index.html
- src/index.tsx
Related Task:
- https://github.com/buerokratt/Chat-Widget/issues/404
> Refactor chat widget basepath
